# Generated by Django 4.0.3 on 2022-06-14 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_book_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='digtal',
            new_name='digital',
        ),
    ]
